[package]
name = "zkp_toolkit"
version = "0.1.0"
edition = "2021"

[lib]
name = "zkp_toolkit"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }
ark-std = "0.4"
ark-ff = "0.4"
ark-ec = "0.4"
ark-bn254 = "0.4"
rand = "0.8"
sha2 = "0.10"
hex = "0.4"
